name: Build

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

env:
  SOLUTION_FILE_PATH: .
  DEFAULT_BRANCH: main

jobs:
  build:
    runs-on: windows-2022
    permissions:
      checks: write
    defaults:
      run:
        working-directory: ${{ github.workspace }} 
    outputs:
      run_id: ${{ job.status.run_id }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0

    - name: Prepare test submodules
      shell: pwsh
      run: |
        ./Scripts/UpdateSubmodules.ps1

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[17.0, ]'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Get nightly version
      id: get-nightly-version
      if: inputs.version == ''
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: true
        TAG_CONTEXT: repo
      
    - name: Determine version
      shell: powershell
      run: |
        if ($env:INPUTS_VERSION -eq "") {
          echo "version=${{ steps.get-nightly-version.outputs.new_tag }}" >> $env:GITHUB_ENV
        } else {
          echo "version=${{ inputs.version }}" >> $env:GITHUB_ENV
        }

    - name: Set VSIX version
      uses: cezarypiatek/VsixVersionAction@1.0
      with:
        version: ${{ env.version }}
        vsix-manifest-file: .\GitTreeFilter\source.extension.vsixmanifest

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
      shell: powershell

    - name: Test
      run: dotnet test ${{env.SOLUTION_FILE_PATH}} --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test results
        path: "**/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Upload GitTreeFilter.vsix
      uses: actions/upload-artifact@v4
      with:
        name: GitTreeFilter.vsix
        path: '.\GitTreeFilter\bin\Release\GitTreeFilter.vsix'
