name: build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  SOLUTION_FILE_PATH: .
  DEFAULT_BRANCH: main

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ github.workspace }} 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0

    - run: |
        git submodule foreach git checkout main
        cd TestResources\TestRepository && git status

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[17.0, ]'

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
      shell: powershell

    - name: Tests
      run:  vstest.console.exe **\*.Tests.dll