name: build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  SOLUTION_FILE_PATH: .
  DEFAULT_BRANCH: main

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ github.workspace }} 

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 0

    - name: Track main branches in submodules
      run: |
        git submodule foreach git checkout main

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[17.0, ]'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Restore NuGet packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m
      shell: powershell

    - name: Run vstests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: GitTreeFilter.Core.Tests.dll
        searchFolder: .\GitTreeFilter.Core.Tests\bin\Debug\
        runInParallel: true

    - name: Publish unit test results
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: GitTreeFilter.Core.Tests
        report_name: unit-tests
        report_title: Unit Test Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: unit-tests.md
        gist_badge_label: 'Unit tests: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}