name: CI

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - release/*
env:
  SOLUTION_FILE_PATH: .
  DEFAULT_BRANCH: main

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    permissions:
      checks: write
  autotag:
    if: github.event.pull_request.merged == true
    needs:
      - build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
        fetch: '+refs/heads/main:refs/remotes/origin/main +refs/heads/${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}'

    - name: Create main
      run: |
        git branch main origin/main
        git branch
        git branch -r

    - name: Default version from main branch
      if: github.event.pull_request.base.ref == 'main'
      run: |
        echo "DefaultVersion=0.0.0" >> $GITHUB_ENV

    - name: Extract major version from release branch
      if: startsWith(github.event.pull_request.base.ref, 'release/')
      run: |
        export MajorVersion=$(echo ${GITHUB_REF#refs/heads/release/v} | cut -d/ -f1)
        export InitialVersion="${MajorVersion}.0.0"
        echo "InitialVersion=$InitialVersion" >> $GITHUB_ENV

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        PRERELEASE: ${{ github.event.pull_request.base.ref == 'main' && 'true' || 'false' }}
        TAG_CONTEXT: branch
        DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
        INITIAL_VERSION: ${{ env.InitialVersion }}
        RELEASE_BRANCHES: release/*
        VERBOSE: true
