name: PullRequest

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    permissions:
      checks: write
    with:
      commit: ${{ github.event.pull_request.merge_commit_sha }}
