name: PublishRelease

on:
  release:
    types: [published]

env:
  VSIX_FILE_NAME: GitTreeFilter-${{ github.event.release.tag_name }}.vsix
  SOURCES_FILE_NAME: Sources.tar.gz

jobs:
  publish:
    if: github.event.release.draft == false && github.event.release.prerelease == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
          fetch-depth: '0'

      - name: Set up Git actions user
        uses: fregante/setup-git-user@v1

      - uses: robinraju/release-downloader@v1
        with:
          releaseId: ${{ github.event.release.id }}
          fileName: ${{ env.VSIX_FILE_NAME }}
          token:  ${{ secrets.GITHUB_TOKEN }}
          tarBall: true
          extract: true

      - name: Get sources root path
        id: get-sources-root
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          TAG_NAME=${TAG_NAME#v}
          echo "sources_root=GitTreeFilter-4-VisualStudio-${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Publish extension to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.2
        with:
          extension-file: ${{ env.VSIX_FILE_NAME }}
          publish-manifest-file: '${{ steps.get-sources-root.outputs.sources_root }}\GitTreeFilter\vs-publish.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
