name: PublishRelease

on:
  release:
    types: [published]

env:
  VSIX_FILE_NAME: GitTreeFilter-${{ github.event.release.tag_name }}.vsix

jobs:
  publish:
    if: github.event.release.draft == false && github.event.release.prerelease == false
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
          fetch-depth: '0'

      - name: Set up Git actions user
        uses: fregante/setup-git-user@v1

      - uses: robinraju/release-downloader@v1
        id: download-release-assets
        with:
          releaseId: ${{ github.event.release.id }}
          fileName: ${{ env.VSIX_FILE_NAME }}
          token:  ${{ secrets.GITHUB_TOKEN }}
          zipBall: true
          extract: false # This uses some weird naming pattern for the extracted content

      - name: List all files recursively
        id: extract-release-assets
        shell: pwsh
        run: |
          Expand-Archive -Path ${{ fromJson(steps.download-release-assets.outputs.downloaded_files)[1] }} -DestinationPath . -PassThru
          Get-ChildItem -Recurse | ForEach-Object { Write-Host $_.FullName }

          $tagName = "${{ github.event.release.tag_name }}"
          $tagName = $tagName -replace "^v"
          "sources_root=GitTreeFilter-4-VisualStudio-$tagName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Publish extension to Marketplace
        uses: cezarypiatek/VsixPublisherAction@0.2
        with:
          extension-file: ${{ env.VSIX_FILE_NAME }}
          publish-manifest-file: '${{ steps.extract-release-assets.outputs.sources_root }}/GitTreeFilter/vs-publish.json'
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
